# Config settings
title: LPub3D
description: An LDraw™ editor for LEGO® style digital building instructions.
theme: jekyll-theme-minimal
timezone: Europe/Paris
baseurl: /lpub3d
permalink: none
port: 8098

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "/assets/images"
      path: "/assets/images/screenshots"
    values:
      image: true

