author:
  name: "Trevor SANDY"

logo:
  link: "https://raw.githubusercontent.com/trevorsandy/lpub3d/master/mainApp/resources/lpub3d128.png"
  alt: "LPub3D-logo"

social:
  - {smbl: "fab", icon: "github", link: "https://www.github.com/trevorsandy"}
  - {smbl: "fab", icon: "linkedin", link: "http://www.linkedin.com/in/trevor-sandy-4193a122/"}
  - {smbl: "fab", icon: "x-twitter", link: "https://x.com/intent/follow?screen_name=tds2142"}
  - {smbl: "fa", icon: "envelope", link: "mailto:trevor.sandy@gmail.com"}

projects:
  obs: "https://build.opensuse.org/package/show/home:trevorsandy/lpub3d"
  sourceforge: "https://sourceforge.net/projects/lpub3d"
